import { Product } from '@/lib/types';

export const featuredProducts: Product[] = [
  {
    id: 'p1',
    slug: 'blushing-beauty',
    name: 'Blushing Beauty Bouquet',
    description: 'A beautiful mix of pink roses and lilies.',
    shortDescription: 'Pink roses and lilies',
    price: 1299,
    originalPrice: 1499,
    images: ['/images/white_lilies.png'],
    image: '/images/white_lilies.png',
    category: 'bouquets',
    occasions: ['anniversary', 'valentines'],
    inStock: true,
    deliveryEligible: true,
    rating: 4.8,
    reviewCount: 124,
    tags: ['roses', 'lilies'],
    isBestseller: true,
    isFeatured: true,
    badge: 'Bestseller',
  },
  {
    id: 'p2',
    slug: 'sunshine-daisies',
    name: 'Sunshine Daisies',
    description: 'Bright and cheerful yellow daisies to light up any room.',
    shortDescription: 'Yellow daisies',
    price: 899,
    images: ['/images/purple_orchids.png'],
    image: '/images/purple_orchids.png',
    category: 'flowers',
    occasions: ['birthday', 'get-well'],
    inStock: true,
    deliveryEligible: true,
    rating: 4.5,
    reviewCount: 89,
    tags: ['daisies', 'yellow'],
    isBestseller: false,
    isFeatured: true,
  },
  {
    id: 'p3',
    slug: 'elegant-orchids',
    name: 'Elegant Purple Orchids',
    description: 'Premium purple orchids in a glass vase.',
    shortDescription: 'Purple orchids in vase',
    price: 1899,
    images: ['/images/purple_orchids.png'],
    image: '/images/purple_orchids.png',
    category: 'arrangements',
    occasions: ['congratulations', 'anniversary'],
    inStock: true,
    deliveryEligible: true,
    rating: 4.9,
    reviewCount: 56,
    tags: ['orchids', 'premium'],
    isBestseller: false,
    isFeatured: true,
    badge: 'Premium',
  },
  {
    id: 'p4',
    slug: 'classic-red-roses',
    name: 'Classic Romance (24 Red Roses)',
    description: 'The ultimate symbol of love - 24 premium red roses.',
    shortDescription: '24 Red Roses',
    price: 2499,
    originalPrice: 2999,
    images: ['/images/red_roses.png'],
    image: '/images/red_roses.png',
    category: 'bouquets',
    occasions: ['valentines', 'anniversary'],
    inStock: true,
    deliveryEligible: true,
    rating: 5.0,
    reviewCount: 210,
    tags: ['roses', 'red'],
    isBestseller: true,
    isFeatured: true,
    badge: 'Most Loved',
  },
];
